name: Test

on: push

env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24"
          elixir-version: "1.12"

      - name: Install Dependencies
        run: |
          mix deps.get

      - name: Run Tests
        run: |
          mix coveralls.json
      
      - name: Upload Coverage Reports
        uses: codecov/codecov-action@v2
        with:
          directory: ./cover
          fail_ci_if_error: true
